# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, uic
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QTableWidgetItem, QAbstractItemView, QHeaderView, QHBoxLayout, QSpacerItem, QSizePolicy
from PyQt5.QtGui import QBrush, QColor, QFont
from PyQt5.QtCore import Qt, QPoint

class View(object):
#This class contains mixed generated code from Qt Designer and hand-written views

    def __init__(self, ratio, window):
        self.ratio = ratio
        self.window = window
        self.setupView(self.window)

    def setupView(self, Form):
        Form.setObjectName("Form")
        Form.resize(int(1920 * self.ratio), int(1080 * self.ratio))
        Form.setMinimumSize(QtCore.QSize(int(1920 * self.ratio), int(1080 * self.ratio)))
        Form.setMaximumSize(QtCore.QSize(int(1920 * self.ratio), int(1080 * self.ratio)))
        Form.setStyleSheet("background-color: #171717;")
        self.quit_button = QtWidgets.QToolButton(Form)
        self.quit_button.setGeometry(QtCore.QRect(int(1890 * self.ratio), 0, int(30 * self.ratio), int(30 * self.ratio)))
        self.quit_button.setStyleSheet("background: #ff5252;\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;"
)
        self.quit_button.setObjectName("quit_button")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(int(30 * self.ratio), int(30 * self.ratio), int(1861 * self.ratio), int(1051 * self.ratio)))
        self.layoutWidget.setObjectName("layoutWidget")
        self.main_layout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.main_layout.setContentsMargins(0, 0, 0, 0)
        self.main_layout.setSpacing(int(20 * self.ratio))
        self.main_layout.setObjectName("main_layout")
        self.tooltip_layout = QtWidgets.QHBoxLayout()
        self.tooltip_layout.setSpacing(int(20 * self.ratio))
        self.tooltip_layout.setObjectName("tooltip_layout")
        self.main_button = QtWidgets.QPushButton(self.layoutWidget)
        self.main_button.setMinimumSize(QtCore.QSize(int(100 * self.ratio), int(100 * self.ratio)))
        self.main_button.setStyleSheet("border-image: url(./resources/logo.png);\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;")
        self.main_button.setText("")
        self.main_button.setObjectName("main_button")
        self.tooltip_layout.addWidget(self.main_button)
        self.favourites_button = QtWidgets.QPushButton(self.layoutWidget)
        
        self.favourites_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(32 * self.ratio)) + "px;")
        self.favourites_button.setObjectName("favourites_button")
        self.tooltip_layout.addWidget(self.favourites_button)
        self.my_portfolio_button = QtWidgets.QPushButton(self.layoutWidget)
       
        self.my_portfolio_button.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(32 * self.ratio)) + "px;")
        self.my_portfolio_button.setObjectName("my_portfolio_button")
        self.tooltip_layout.addWidget(self.my_portfolio_button)
        spacerItem = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.tooltip_layout.addItem(spacerItem)

        self.tooltip_search_text = QtWidgets.QLineEdit(self.layoutWidget, placeholderText='Search...')
        self.tooltip_search_text.setMaxLength(30)
        # self.details_portfolio_bought_amount_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tooltip_search_text.setMinimumSize(QtCore.QSize(int(250 * self.ratio), int(25 * self.ratio)))
        self.tooltip_search_text.setMaximumSize(QtCore.QSize(int(250 * self.ratio), int(25 * self.ratio)))
        self.tooltip_search_text.setStyleSheet("background: #232323;\n"
"border: 1px solid;\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;\n"
"")
        self.tooltip_search_text.setObjectName("tooltip_search_text")
        self.tooltip_layout.addWidget(self.tooltip_search_text)

        self.tooltip_search_button = QtWidgets.QPushButton(self.layoutWidget)
        
        self.tooltip_search_button.setMinimumSize(QtCore.QSize(int(40 * self.ratio), int(40 * self.ratio)))
        self.tooltip_search_button.setMaximumSize(QtCore.QSize(int(40 * self.ratio), int(40 * self.ratio)))
        self.tooltip_search_button.setStyleSheet("border-image: url(./resources/search.png);\n"
"background: rgba(0, 0, 0, 0);")
        self.tooltip_search_button.setText("")
        self.tooltip_search_button.setObjectName("tooltip_search_button")
        self.tooltip_layout.addWidget(self.tooltip_search_button)

        
        self.main_layout.addLayout(self.tooltip_layout)

        self.toolbar_line = QtWidgets.QFrame(self.layoutWidget)
        self.toolbar_line.setMinimumSize(QtCore.QSize(0, 1))
        self.toolbar_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.toolbar_line.setStyleSheet("background: #808080")
        self.toolbar_line.setFrameShape(QtWidgets.QFrame.HLine)
        self.toolbar_line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.toolbar_line.setObjectName("toolbar_line")
        self.main_layout.addWidget(self.toolbar_line)
        self.stackedWidget = QtWidgets.QStackedWidget(self.layoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.master_widget = QtWidgets.QWidget()
        self.master_widget.setObjectName("master_widget")
        self.layoutWidget1 = QtWidgets.QWidget(self.master_widget)
        self.layoutWidget1.setGeometry(QtCore.QRect(int(20 * self.ratio), int(10 * self.ratio), int(1821 * self.ratio), int(901 * self.ratio)))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.master_layout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.master_layout.setContentsMargins(0, 0, 0, 0)
        self.master_layout.setSpacing(int(20 * self.ratio))
        self.master_layout.setObjectName("master_layout")
        self.market_cap_label_layout = QtWidgets.QHBoxLayout()
        self.market_cap_label_layout.setSpacing(int(4 * self.ratio))
        self.market_cap_label_layout.setObjectName("market_cap_label_layout")
        self.market_cap_prefix_label = QtWidgets.QLabel(self.layoutWidget1)
        self.market_cap_prefix_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;")
        self.market_cap_prefix_label.setObjectName("market_cap_prefix_label")
        self.market_cap_label_layout.addWidget(self.market_cap_prefix_label)
        self.market_cap_suffix_label = QtWidgets.QLabel(self.layoutWidget1)
        self.market_cap_suffix_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;")
        self.market_cap_suffix_label.setObjectName("market_cap_suffix_label")
        self.market_cap_label_layout.addWidget(self.market_cap_suffix_label)
        spacerItem1 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.market_cap_label_layout.addItem(spacerItem1)
        self.master_layout.addLayout(self.market_cap_label_layout)
        self.global_widgets_layout = QtWidgets.QHBoxLayout()
        self.global_widgets_layout.setSpacing(int(20 * self.ratio))
        self.global_widgets_layout.setObjectName("global_widgets_layout")
        self.market_cap_widget = QtWidgets.QWidget(self.layoutWidget1)
        self.market_cap_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.market_cap_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.market_cap_widget.setObjectName("market_cap_widget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.market_cap_widget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.market_cap_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.market_cap_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.market_cap_widget_hlayout.setObjectName("market_cap_widget_hlayout")
        self.market_cap_widget_vlayout = QtWidgets.QVBoxLayout()
        self.market_cap_widget_vlayout.setObjectName("market_cap_widget_vlayout")
        self.market_cap_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.market_cap_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.market_cap_widget_value.setObjectName("market_cap_widget_value")
        self.market_cap_widget_vlayout.addWidget(self.market_cap_widget_value)
        self.market_cap_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.market_cap_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.market_cap_widget_label.setObjectName("market_cap_widget_label")
        self.market_cap_widget_vlayout.addWidget(self.market_cap_widget_label)
        self.market_cap_widget_vlayout.setStretch(1, 1)
        self.market_cap_widget_hlayout.addLayout(self.market_cap_widget_vlayout)
        self.global_widgets_layout.addWidget(self.market_cap_widget)
        self.trading_volume_widget = QtWidgets.QWidget(self.layoutWidget1)
        self.trading_volume_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.trading_volume_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.trading_volume_widget.setObjectName("trading_volume_widget")
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.trading_volume_widget)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.trading_volume_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.trading_volume_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.trading_volume_widget_hlayout.setObjectName("trading_volume_widget_hlayout")
        self.trading_volume_widget_vlayout = QtWidgets.QVBoxLayout()
        self.trading_volume_widget_vlayout.setObjectName("trading_volume_widget_vlayout")
        self.trading_volume_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.trading_volume_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.trading_volume_widget_value.setObjectName("trading_volume_widget_value")
        self.trading_volume_widget_vlayout.addWidget(self.trading_volume_widget_value)
        self.trading_volume_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.trading_volume_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.trading_volume_widget_label.setObjectName("trading_volume_widget_label")
        self.trading_volume_widget_vlayout.addWidget(self.trading_volume_widget_label)
        self.trading_volume_widget_vlayout.setStretch(0, 2)
        self.trading_volume_widget_hlayout.addLayout(self.trading_volume_widget_vlayout)
        self.global_widgets_layout.addWidget(self.trading_volume_widget)
        self.btc_dominance_widget = QtWidgets.QWidget(self.layoutWidget1)
        self.btc_dominance_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.btc_dominance_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.btc_dominance_widget.setObjectName("btc_dominance_widget")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.btc_dominance_widget)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 0, int(291 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.btc_dominance_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.btc_dominance_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(15 * self.ratio), int(20 * self.ratio))
        self.btc_dominance_widget_hlayout.setObjectName("btc_dominance_widget_hlayout")
        self.btc_dominance_widget_vlayout = QtWidgets.QVBoxLayout()
        self.btc_dominance_widget_vlayout.setContentsMargins(0, 0, 0, 0)
        self.btc_dominance_widget_vlayout.setObjectName("btc_dominance_widget_vlayout")
        self.btc_dominance_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.btc_dominance_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.btc_dominance_widget_value.setObjectName("btc_dominance_widget_value")
        self.btc_dominance_widget_vlayout.addWidget(self.btc_dominance_widget_value)
        self.btc_dominance_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.btc_dominance_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.btc_dominance_widget_label.setObjectName("btc_dominance_widget_label")
        self.btc_dominance_widget_vlayout.addWidget(self.btc_dominance_widget_label)
        self.btc_dominance_widget_vlayout.setStretch(0, 2)
        self.btc_dominance_widget_vlayout.setStretch(1, 1)
        self.btc_dominance_widget_hlayout.addLayout(self.btc_dominance_widget_vlayout)
        self.global_widgets_layout.addWidget(self.btc_dominance_widget)
        self.number_of_coins_widget = QtWidgets.QWidget(self.layoutWidget1)
        self.number_of_coins_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.number_of_coins_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.number_of_coins_widget.setObjectName("number_of_coins_widget")
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.number_of_coins_widget)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.number_of_coins_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.number_of_coins_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.number_of_coins_widget_hlayout.setObjectName("number_of_coins_widget_hlayout")
        self.number_of_coins_widget_vlayout = QtWidgets.QVBoxLayout()
        self.number_of_coins_widget_vlayout.setObjectName("number_of_coins_widget_vlayout")
        self.number_of_coins_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.number_of_coins_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.number_of_coins_widget_value.setObjectName("number_of_coins_widget_value")
        self.number_of_coins_widget_vlayout.addWidget(self.number_of_coins_widget_value)
        self.number_of_coins_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_5)
        self.number_of_coins_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.number_of_coins_widget_label.setObjectName("number_of_coins_widget_label")
        self.number_of_coins_widget_vlayout.addWidget(self.number_of_coins_widget_label)
        self.number_of_coins_widget_vlayout.setStretch(0, 2)
        self.number_of_coins_widget_vlayout.setStretch(1, 1)
        self.number_of_coins_widget_hlayout.addLayout(self.number_of_coins_widget_vlayout)
        self.global_widgets_layout.addWidget(self.number_of_coins_widget)
        spacerItem2 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.global_widgets_layout.addItem(spacerItem2)
        self.global_widgets_layout.setStretch(0, 1)
        self.global_widgets_layout.setStretch(1, 1)
        self.global_widgets_layout.setStretch(2, 1)
        self.global_widgets_layout.setStretch(3, 1)
        self.global_widgets_layout.setStretch(4, 2)
        self.master_layout.addLayout(self.global_widgets_layout)
        self.master_table_widget = QtWidgets.QTableWidget(self.layoutWidget1)
        self.master_table_widget.setAutoFillBackground(False)
        self.master_table_widget.setStyleSheet("QHeaderView::section {\n"
"    background-color:  #232323;\n"
"    border: none;\n"
"    height: " + str(int(32 * self.ratio)) + "px;\n"
"    color:white;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: " + str(int(16 * self.ratio)) + "px;\n"
"    font-weight: 500;\n"
"}\n"
"QFrame {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}    \n"
"QTableWidget  {\n"
"    gridline-color: #232323;\n"
"}    \n"
"")
        self.master_table_widget.setObjectName("master_table_widget")
        self.master_table_widget.setColumnCount(8)
        # self.master_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.master_table_widget.setHorizontalHeaderItem(7, item)
        # self.master_table_widget.horizontalHeader().setDefaultSectionSize(int(200 * self.ratio))
        self.master_table_widget.horizontalHeader().setHighlightSections(True)
        # self.master_table_widget.horizontalHeader().setMinimumSectionSize(int(200 * self.ratio))
        self.master_table_widget.horizontalHeader().setStretchLastSection(True)
        self.master_table_widget.verticalHeader().setVisible(False)
        # self.master_table_widget.verticalHeader().setMinimumSectionSize(int(30 * self.ratio))
        self.master_table_widget.verticalHeader().setSortIndicatorShown(False)
        self.master_table_widget.verticalHeader().setStretchLastSection(False)
        self.master_layout.addWidget(self.master_table_widget)
        self.master_layout.setStretch(1, 1)
        self.master_layout.setStretch(2, 1)
        self.stackedWidget.addWidget(self.master_widget)
        self.details_widget = QtWidgets.QWidget()
        self.details_widget.setObjectName("details_widget")
        self.layoutWidget2 = QtWidgets.QWidget(self.details_widget)
        self.layoutWidget2.setGeometry(QtCore.QRect(int(20 * self.ratio), int(10 * self.ratio), int(1821 * self.ratio), int(901 * self.ratio)))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.details_layout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.details_layout.setContentsMargins(0, 0, 0, 0)
        self.details_layout.setSpacing(int(9 * self.ratio))
        self.details_layout.setObjectName("details_layout")
        self.rank_label = QtWidgets.QLabel(self.layoutWidget2)
        self.rank_label.setMinimumSize(QtCore.QSize(int(70 * self.ratio), int(30 * self.ratio)))
        self.rank_label.setMaximumSize(QtCore.QSize(int(70 * self.ratio), int(30 * self.ratio)))
        self.rank_label.setStyleSheet("background: #232323;\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(14 * self.ratio)) + "px;\n"
"border-radius: " + str(int(9 * self.ratio)) + "px;\n"
"font-weight: 500;")
        self.rank_label.setAlignment(QtCore.Qt.AlignCenter)
        self.rank_label.setObjectName("rank_label")
        self.details_layout.addWidget(self.rank_label)
        self.details_coin_id_layout = QtWidgets.QHBoxLayout()
        self.details_coin_id_layout.setSpacing(int(8 * self.ratio))
        self.details_coin_id_layout.setObjectName("details_coin_id_layout")
        self.details_coin_logo_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_coin_logo_label.setMinimumSize(QtCore.QSize(int(50 * self.ratio), int(50 * self.ratio)))
        self.details_coin_logo_label.setMaximumSize(QtCore.QSize(int(50 * self.ratio), int(50 * self.ratio)))
#         self.details_coin_logo_label.setStyleSheet("border-image: url(./resources/logo.png);\n"
# "border-radius: 50%;\n"
# "background: rgba(0, 0, 0, 0);")
        self.details_coin_logo_label.setText("")
        self.details_coin_logo_label.setObjectName("details_coin_logo_label")
        self.details_coin_id_layout.addWidget(self.details_coin_logo_label)
        self.details_coin_name_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_coin_name_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;\n"
"font-weight: bold;")
        self.details_coin_name_label.setObjectName("details_coin_name_label")
        self.details_coin_id_layout.addWidget(self.details_coin_name_label)
        self.details_coin_symbol_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_coin_symbol_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;\n"
"font-weight: 350;")
        self.details_coin_symbol_label.setObjectName("details_coin_symbol_label")
        self.details_coin_id_layout.addWidget(self.details_coin_symbol_label)
        self.details_star_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.details_star_button.setMinimumSize(QtCore.QSize(int(30 * self.ratio), int(30 * self.ratio)))
        self.details_star_button.setMaximumSize(QtCore.QSize(int(30 * self.ratio), int(30 * self.ratio)))
        self.details_star_button.setStyleSheet("border-image: url(./resources/star_empty.png);\n"
"background: rgba(0, 0, 0, 0);")
        self.details_star_button.setText("")
        self.details_star_button.setObjectName("details_star_button")
        self.details_coin_id_layout.addWidget(self.details_star_button)
        self.details_plus_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.details_plus_button.setMinimumSize(QtCore.QSize(int(25 * self.ratio), int(25 * self.ratio)))
        self.details_plus_button.setMaximumSize(QtCore.QSize(int(25 * self.ratio), int(25 * self.ratio)))
        self.details_plus_button.setStyleSheet("border-image: url(./resources/plus_fill.png);\n"
"background: rgba(0, 0, 0, 0);")
        self.details_plus_button.setText("")
        self.details_plus_button.setObjectName("details_plus_button")
        self.details_coin_id_layout.addWidget(self.details_plus_button)

        self.details_portfolio_bought_amount_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_portfolio_bought_amount_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(16 * self.ratio)) + "px;\n"
"font-weight: bold;")
        self.details_portfolio_bought_amount_label.setObjectName("details_portfolio_bought_amount_label")
        self.details_portfolio_bought_amount_label.hide()
        self.details_coin_id_layout.addWidget(self.details_portfolio_bought_amount_label)
        self.details_portfolio_bought_amount_text = QtWidgets.QLineEdit(placeholderText='Amount')
        self.details_portfolio_bought_amount_text.setMaxLength(10)
        # self.details_portfolio_bought_amount_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.details_portfolio_bought_amount_text.setMinimumSize(QtCore.QSize(int(100 * self.ratio), int(25 * self.ratio)))
        self.details_portfolio_bought_amount_text.setMaximumSize(QtCore.QSize(int(100 * self.ratio), int(25 * self.ratio)))
        self.details_portfolio_bought_amount_text.setStyleSheet("background: #232323;\n"
"border: 1px solid;\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(16 * self.ratio)) + "px;\n"
"font-weight: bold;\n"
"")
        self.details_portfolio_bought_amount_text.setObjectName("details_portfolio_bought_amount_text")
        self.details_portfolio_bought_amount_text.hide()
        self.details_coin_id_layout.addWidget(self.details_portfolio_bought_amount_text)

        self.details_portfolio_price_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_portfolio_price_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(16 * self.ratio)) + "px;\n"
"font-weight: bold;")
        self.details_portfolio_price_label.setObjectName("details_portfolio_price_label")
        self.details_portfolio_price_label.hide()
        self.details_coin_id_layout.addWidget(self.details_portfolio_price_label)
        
        self.details_portfolio_price_text = QtWidgets.QLineEdit(placeholderText='Unit price')
        self.details_portfolio_price_text.setMaxLength(10)
        # self.details_portfolio_bought_amount_text.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.details_portfolio_price_text.setMinimumSize(QtCore.QSize(int(100 * self.ratio), int(25 * self.ratio)))
        self.details_portfolio_price_text.setMaximumSize(QtCore.QSize(int(100 * self.ratio), int(25 * self.ratio)))
        self.details_portfolio_price_text.setStyleSheet("background: #232323;\n"
"border: 1px solid;\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(16 * self.ratio)) + "px;\n"
"font-weight: bold;\n"
"")
        self.details_portfolio_price_text.setObjectName("details_portfolio_price_text")
        self.details_portfolio_price_text.hide()
        self.details_coin_id_layout.addWidget(self.details_portfolio_price_text)
        

        self.details_portfolio_tick_button = QtWidgets.QPushButton(self.layoutWidget2)
        self.details_portfolio_tick_button.setMinimumSize(QtCore.QSize(int(25 * self.ratio), int(25 * self.ratio)))
        self.details_portfolio_tick_button.setMaximumSize(QtCore.QSize(int(25 * self.ratio), int(25 * self.ratio)))
        self.details_portfolio_tick_button.setStyleSheet("border-image: url(./resources/tick.png);\n"
"background: rgba(0, 0, 0, 0);")
        self.details_portfolio_tick_button.setText("")
        self.details_portfolio_tick_button.setObjectName("details_portfolio_tick_button")
        self.details_portfolio_tick_button.hide()
        self.details_coin_id_layout.addWidget(self.details_portfolio_tick_button)

        spacerItem3 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.details_coin_id_layout.addItem(spacerItem3)
        self.details_layout.addLayout(self.details_coin_id_layout)
        self.details_coin_price_layout = QtWidgets.QHBoxLayout()
        self.details_coin_price_layout.setSpacing(int(8 * self.ratio))
        self.details_coin_price_layout.setObjectName("details_coin_price_layout")
        self.details_coin_price_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_coin_price_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(32 * self.ratio)) + "px;\n"
"font-weight: bold;")
        self.details_coin_price_label.setObjectName("details_coin_price_label")
        self.details_coin_price_layout.addWidget(self.details_coin_price_label)
        self.details_coin_change_label = QtWidgets.QLabel(self.layoutWidget2)
        self.details_coin_change_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: lime;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;\n"
"font-weight: bold;")
        self.details_coin_change_label.setObjectName("details_coin_change_label")
        self.details_coin_price_layout.addWidget(self.details_coin_change_label)
        spacerItem4 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.details_coin_price_layout.addItem(spacerItem4)
        self.details_layout.addLayout(self.details_coin_price_layout)
        self.details_coin_widgets_layout = QtWidgets.QHBoxLayout()
        self.details_coin_widgets_layout.setSpacing(int(20 * self.ratio))
        self.details_coin_widgets_layout.setObjectName("details_coin_widgets_layout")
        self.details_market_cap_widget = QtWidgets.QWidget(self.layoutWidget2)
        self.details_market_cap_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.details_market_cap_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.details_market_cap_widget.setObjectName("details_market_cap_widget")
        self.horizontalLayoutWidget_10 = QtWidgets.QWidget(self.details_market_cap_widget)
        self.horizontalLayoutWidget_10.setGeometry(QtCore.QRect(0, 0, int(291 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_10.setObjectName("horizontalLayoutWidget_10")
        self.details_market_cap_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_10)
        self.details_market_cap_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.details_market_cap_widget_hlayout.setObjectName("details_market_cap_widget_hlayout")
        self.details_market_cap_widget_vlayout = QtWidgets.QVBoxLayout()
        self.details_market_cap_widget_vlayout.setObjectName("details_market_cap_widget_vlayout")
        self.details_market_cap_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.details_market_cap_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.details_market_cap_widget_value.setObjectName("details_market_cap_widget_value")
        self.details_market_cap_widget_vlayout.addWidget(self.details_market_cap_widget_value)
        self.details_market_cap_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_10)
        self.details_market_cap_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.details_market_cap_widget_label.setObjectName("details_market_cap_widget_label")
        self.details_market_cap_widget_vlayout.addWidget(self.details_market_cap_widget_label)
        self.details_market_cap_widget_vlayout.setStretch(1, 1)
        self.details_market_cap_widget_hlayout.addLayout(self.details_market_cap_widget_vlayout)
        self.details_coin_widgets_layout.addWidget(self.details_market_cap_widget)
        self.details_trading_volume_widget = QtWidgets.QWidget(self.layoutWidget2)
        self.details_trading_volume_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.details_trading_volume_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.details_trading_volume_widget.setObjectName("details_trading_volume_widget")
        self.horizontalLayoutWidget_11 = QtWidgets.QWidget(self.details_trading_volume_widget)
        self.horizontalLayoutWidget_11.setGeometry(QtCore.QRect(0, 0, int(291 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_11.setObjectName("horizontalLayoutWidget_11")
        self.details_trading_volume_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_11)
        self.details_trading_volume_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.details_trading_volume_widget_hlayout.setObjectName("details_trading_volume_widget_hlayout")
        self.details_trading_volume_widget_vlayout = QtWidgets.QVBoxLayout()
        self.details_trading_volume_widget_vlayout.setObjectName("details_trading_volume_widget_vlayout")
        self.details_trading_volume_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.details_trading_volume_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.details_trading_volume_widget_value.setObjectName("details_trading_volume_widget_value")
        self.details_trading_volume_widget_vlayout.addWidget(self.details_trading_volume_widget_value)
        self.details_trading_volume_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_11)
        self.details_trading_volume_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.details_trading_volume_widget_label.setObjectName("details_trading_volume_widget_label")
        self.details_trading_volume_widget_vlayout.addWidget(self.details_trading_volume_widget_label)
        self.details_trading_volume_widget_vlayout.setStretch(0, 2)
        self.details_trading_volume_widget_hlayout.addLayout(self.details_trading_volume_widget_vlayout)
        self.details_coin_widgets_layout.addWidget(self.details_trading_volume_widget)
        self.details_circulating_supply_widget = QtWidgets.QWidget(self.layoutWidget2)
        self.details_circulating_supply_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.details_circulating_supply_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.details_circulating_supply_widget.setObjectName("details_circulating_supply_widget")
        self.horizontalLayoutWidget_12 = QtWidgets.QWidget(self.details_circulating_supply_widget)
        self.horizontalLayoutWidget_12.setGeometry(QtCore.QRect(0, 0, int(291 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_12.setObjectName("horizontalLayoutWidget_12")
        self.details_circulating_supply_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_12)
        self.details_circulating_supply_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.details_circulating_supply_widget_hlayout.setObjectName("details_circulating_supply_widget_hlayout")
        self.details_circulating_supply_widget_vlayout = QtWidgets.QVBoxLayout()
        self.details_circulating_supply_widget_vlayout.setContentsMargins(0, 0, 0, 0)
        self.details_circulating_supply_widget_vlayout.setObjectName("details_circulating_supply_widget_vlayout")
        self.details_circulating_supply_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.details_circulating_supply_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.details_circulating_supply_widget_value.setObjectName("details_circulating_supply_widget_value")
        self.details_circulating_supply_widget_vlayout.addWidget(self.details_circulating_supply_widget_value)
        self.details_circulating_supply_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_12)
        self.details_circulating_supply_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.details_circulating_supply_widget_label.setObjectName("details_circulating_supply_widget_label")
        self.details_circulating_supply_widget_vlayout.addWidget(self.details_circulating_supply_widget_label)
        self.details_circulating_supply_widget_vlayout.setStretch(0, 2)
        self.details_circulating_supply_widget_vlayout.setStretch(1, 1)
        self.details_circulating_supply_widget_hlayout.addLayout(self.details_circulating_supply_widget_vlayout)
        self.details_coin_widgets_layout.addWidget(self.details_circulating_supply_widget)
        self.details_all_time_high_widget = QtWidgets.QWidget(self.layoutWidget2)
        self.details_all_time_high_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.details_all_time_high_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.details_all_time_high_widget.setObjectName("details_all_time_high_widget")
        self.horizontalLayoutWidget_13 = QtWidgets.QWidget(self.details_all_time_high_widget)
        self.horizontalLayoutWidget_13.setGeometry(QtCore.QRect(0, 0, int(291 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_13.setObjectName("horizontalLayoutWidget_13")
        self.details_all_time_high_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_13)
        self.details_all_time_high_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.details_all_time_high_widget_hlayout.setObjectName("details_all_time_high_widget_hlayout")
        self.details_all_time_high_widget_vlayout = QtWidgets.QVBoxLayout()
        self.details_all_time_high_widget_vlayout.setObjectName("details_all_time_high_widget_vlayout")
        self.details_all_time_high_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.details_all_time_high_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.details_all_time_high_widget_value.setObjectName("details_all_time_high_widget_value")
        self.details_all_time_high_widget_vlayout.addWidget(self.details_all_time_high_widget_value)
        self.details_all_time_high_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_13)
        self.details_all_time_high_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.details_all_time_high_widget_label.setObjectName("details_all_time_high_widget_label")
        self.details_all_time_high_widget_vlayout.addWidget(self.details_all_time_high_widget_label)
        self.details_all_time_high_widget_vlayout.setStretch(0, 2)
        self.details_all_time_high_widget_vlayout.setStretch(1, 1)
        self.details_all_time_high_widget_hlayout.addLayout(self.details_all_time_high_widget_vlayout)
        self.details_coin_widgets_layout.addWidget(self.details_all_time_high_widget)
        self.details_all_time_low_widget = QtWidgets.QWidget(self.layoutWidget2)
        self.details_all_time_low_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.details_all_time_low_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.details_all_time_low_widget.setObjectName("details_all_time_low_widget")
        self.horizontalLayoutWidget_14 = QtWidgets.QWidget(self.details_all_time_low_widget)
        self.horizontalLayoutWidget_14.setGeometry(QtCore.QRect(0, 0, int(291 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_14.setObjectName("horizontalLayoutWidget_14")
        self.details_all_time_low_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_14)
        self.details_all_time_low_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.details_all_time_low_widget_hlayout.setObjectName("details_all_time_low_widget_hlayout")
        self.details_all_time_low_widget_vlayout = QtWidgets.QVBoxLayout()
        self.details_all_time_low_widget_vlayout.setObjectName("details_all_time_low_widget_vlayout")
        self.details_all_time_low_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.details_all_time_low_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.details_all_time_low_widget_value.setObjectName("details_all_time_low_widget_value")
        self.details_all_time_low_widget_vlayout.addWidget(self.details_all_time_low_widget_value)
        self.details_all_time_low_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_14)
        self.details_all_time_low_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.details_all_time_low_widget_label.setObjectName("details_all_time_low_widget_label")
        self.details_all_time_low_widget_vlayout.addWidget(self.details_all_time_low_widget_label)
        self.details_all_time_low_widget_vlayout.setStretch(0, 2)
        self.details_all_time_low_widget_hlayout.addLayout(self.details_all_time_low_widget_vlayout)
        self.details_coin_widgets_layout.addWidget(self.details_all_time_low_widget)
        spacerItem5 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.details_coin_widgets_layout.addItem(spacerItem5)
        self.details_coin_widgets_layout.setStretch(0, 20)
        self.details_coin_widgets_layout.setStretch(1, 20)
        self.details_coin_widgets_layout.setStretch(2, 20)
        self.details_coin_widgets_layout.setStretch(3, 20)
        self.details_coin_widgets_layout.setStretch(4, 20)
        self.details_coin_widgets_layout.setStretch(5, 18)
        self.details_layout.addLayout(self.details_coin_widgets_layout)
        self.matplotlib_widget = QtWidgets.QWidget(self.layoutWidget2)
        self.matplotlib_widget.setMinimumSize(QtCore.QSize(0, int(500 * self.ratio)))
        # self.matplotlib_widget.setMaximumSize(QtCore.QSize(0, int(500 * self.ratio)))
        # self.matplotlib_widget.setStyleSheet("background: rgb(85, 0, 0)")
        self.matplotlib_widget.setObjectName("matplotlib_widget")
        self.plot_container_layout = QtWidgets.QVBoxLayout()
        self.matplotlib_widget.setLayout(self.plot_container_layout)
        self.details_layout.addWidget(self.matplotlib_widget)
        self.time_change_table = QtWidgets.QTableWidget(self.layoutWidget2)
        self.time_change_table.setContentsMargins(0, 0, 0, 0)
        self.time_change_table.setMinimumSize(QtCore.QSize(int(900 * self.ratio), int(64 * self.ratio)))
        self.time_change_table.setMaximumSize(QtCore.QSize(16777215, int(96 * self.ratio)))
        self.time_change_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.time_change_table.setStyleSheet("QHeaderView::section {\n"
"    background-color:  #232323;\n"
"    border: none;\n"
"    height: " + str(int(32 * self.ratio)) + "px;\n"
"    color:white;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: " + str(int(16 * self.ratio)) + "px;\n"
"    font-weight: 500;\n"
"}\n"
"QFrame {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"    border-color: gray;\n"
"}    \n"
"QTableWidget  {\n"
"    gridline-color: #232323;\n"
"}    \n"
"")
        self.time_change_table.setDragDropOverwriteMode(False)
        self.time_change_table.setObjectName("time_change_table")
        self.time_change_table.setColumnCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.time_change_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_change_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_change_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_change_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_change_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.time_change_table.setHorizontalHeaderItem(5, item)

        self.time_change_table.horizontalHeader().setDefaultSectionSize(int(150 * self.ratio))
        self.time_change_table.horizontalHeader().setMinimumSectionSize(int(150 * self.ratio))
        self.time_change_table.verticalHeader().setMinimumSectionSize(int(32 * self.ratio))
        self.time_change_table.verticalHeader().setVisible(False)
        self.time_change_table.setRowCount(1)
        self.time_change_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.time_change_table.setFocusPolicy(Qt.NoFocus)
        self.time_change_table.setSelectionMode(QAbstractItemView.NoSelection)       
        self.time_change_table.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.time_change_table.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.time_change_table.horizontalHeader().setSectionResizeMode(QHeaderView.Fixed)
        self.time_change_table.verticalHeader().setSectionResizeMode(QHeaderView.Fixed)

        self.details_layout.addWidget(self.time_change_table, 0, QtCore.Qt.AlignHCenter)
        spacerItem6 = QtWidgets.QSpacerItem(int(20 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.details_layout.addItem(spacerItem6)
        self.details_layout.setStretch(3, 1)


        self.stackedWidget.addWidget(self.details_widget)
        self.favourites_widget = QtWidgets.QWidget()
        self.favourites_widget.setObjectName("favourites_widget")
        self.layoutWidget_2 = QtWidgets.QWidget(self.favourites_widget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(int(20 * self.ratio), int(10 * self.ratio), int(1821 * self.ratio), int(901 * self.ratio)))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.favourites_layout = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.favourites_layout.setContentsMargins(0, 0, 0, 0)
        self.favourites_layout.setSpacing(int(20 * self.ratio))
        self.favourites_layout.setObjectName("favourites_layout")
        self.favourites_number_of_favourite_coins_layout = QtWidgets.QHBoxLayout()
        self.favourites_number_of_favourite_coins_layout.setSpacing(int(6 * self.ratio))
        self.favourites_number_of_favourite_coins_layout.setObjectName("favourites_number_of_favourite_coins_layout")
        self.favourites_number_of_favourite_coins_label = QtWidgets.QLabel(self.layoutWidget_2)
        self.favourites_number_of_favourite_coins_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;")
        self.favourites_number_of_favourite_coins_label.setObjectName("favourites_number_of_favourite_coins_label")
        self.favourites_number_of_favourite_coins_layout.addWidget(self.favourites_number_of_favourite_coins_label)
        self.favourites_number_of_favourite_coins_value = QtWidgets.QLabel(self.layoutWidget_2)
        self.favourites_number_of_favourite_coins_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(20 * self.ratio)) + "px;")
        self.favourites_number_of_favourite_coins_value.setObjectName("favourites_number_of_favourite_coins_value")
        self.favourites_number_of_favourite_coins_layout.addWidget(self.favourites_number_of_favourite_coins_value)
        spacerItem7 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.favourites_number_of_favourite_coins_layout.addItem(spacerItem7)
        self.favourites_layout.addLayout(self.favourites_number_of_favourite_coins_layout)
        self.favourites_table = QtWidgets.QTableWidget(self.layoutWidget_2)
        self.favourites_table.setAutoFillBackground(False)
        self.favourites_table.setStyleSheet("QHeaderView::section {\n"
"    background-color:  #232323;\n"
"    border: none;\n"
"    height: " + str(int(32 * self.ratio)) + "px;\n"
"    color:white;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: " + str(int(16 * self.ratio)) + "px;\n"
"    font-weight: 500;\n"
"}\n"
"QFrame {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}    \n"
"QTableWidget  {\n"
"    gridline-color: #232323;\n"
"}    \n"
"")
        self.favourites_table.setObjectName("favourites_table")
        self.favourites_table.setColumnCount(8)
        self.favourites_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.favourites_table.setHorizontalHeaderItem(7, item)
        self.favourites_table.horizontalHeader().setDefaultSectionSize(int(200 * self.ratio))
        self.favourites_table.horizontalHeader().setHighlightSections(True)
        # self.favourites_table.horizontalHeader().setMinimumSectionSize(int(200 * self.ratio))
        self.favourites_table.horizontalHeader().setStretchLastSection(True)
        self.favourites_table.verticalHeader().setVisible(False)
        # self.favourites_table.verticalHeader().setMinimumSectionSize(int(30 * self.ratio))
        self.favourites_table.verticalHeader().setSortIndicatorShown(False)
        self.favourites_table.verticalHeader().setStretchLastSection(False)
        self.favourites_layout.addWidget(self.favourites_table)
        self.favourites_layout.setStretch(1, 1)
        self.stackedWidget.addWidget(self.favourites_widget)
        self.portfolio_widget = QtWidgets.QWidget()
        self.portfolio_widget.setObjectName("portfolio_widget")
        self.layoutWidget_3 = QtWidgets.QWidget(self.portfolio_widget)
        self.layoutWidget_3.setGeometry(QtCore.QRect(int(20 * self.ratio), int(10 * self.ratio), int(1821 * self.ratio), int(901 * self.ratio)))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.portfolio_layout = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.portfolio_layout.setContentsMargins(0, 0, 0, 0)
        self.portfolio_layout.setSpacing(int(20 * self.ratio))
        self.portfolio_layout.setObjectName("portfolio_layout")
        self.portfolio_global_widget_layout = QtWidgets.QHBoxLayout()
        self.portfolio_global_widget_layout.setSpacing(int(20 * self.ratio))
        self.portfolio_global_widget_layout.setObjectName("portfolio_global_widget_layout")
        self.portfolio_total_balance_widget = QtWidgets.QWidget(self.layoutWidget_3)
        self.portfolio_total_balance_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.portfolio_total_balance_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.portfolio_total_balance_widget.setObjectName("portfolio_total_balance_widget")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.portfolio_total_balance_widget)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.portfolio_total_balance_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.portfolio_total_balance_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.portfolio_total_balance_widget_hlayout.setObjectName("portfolio_total_balance_widget_hlayout")
        self.portfolio_total_balance_widget_vlayout = QtWidgets.QVBoxLayout()
        self.portfolio_total_balance_widget_vlayout.setObjectName("portfolio_total_balance_widget_vlayout")
        self.portfolio_total_balance_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.portfolio_total_balance_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.portfolio_total_balance_widget_value.setObjectName("portfolio_total_balance_widget_value")
        self.portfolio_total_balance_widget_vlayout.addWidget(self.portfolio_total_balance_widget_value)
        self.portfolio_total_balance_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.portfolio_total_balance_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.portfolio_total_balance_widget_label.setObjectName("portfolio_total_balance_widget_label")
        self.portfolio_total_balance_widget_vlayout.addWidget(self.portfolio_total_balance_widget_label)
        self.portfolio_total_balance_widget_vlayout.setStretch(1, 1)
        self.portfolio_total_balance_widget_hlayout.addLayout(self.portfolio_total_balance_widget_vlayout)
        self.portfolio_global_widget_layout.addWidget(self.portfolio_total_balance_widget)
        self.portfolio_change_widget = QtWidgets.QWidget(self.layoutWidget_3)
        self.portfolio_change_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.portfolio_change_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.portfolio_change_widget.setObjectName("portfolio_change_widget")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.portfolio_change_widget)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.portfolio_change_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.portfolio_change_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.portfolio_change_widget_hlayout.setObjectName("portfolio_change_widget_hlayout")
        self.portfolio_change_widget_vlayout = QtWidgets.QVBoxLayout()
        self.portfolio_change_widget_vlayout.setObjectName("portfolio_change_widget_vlayout")
        self.portfolio_change_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.portfolio_change_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.portfolio_change_widget_value.setObjectName("portfolio_change_widget_value")
        self.portfolio_change_widget_vlayout.addWidget(self.portfolio_change_widget_value)
        self.portfolio_change_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_7)
        self.portfolio_change_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.portfolio_change_widget_label.setObjectName("portfolio_change_widget_label")
        self.portfolio_change_widget_vlayout.addWidget(self.portfolio_change_widget_label)
        self.portfolio_change_widget_vlayout.setStretch(0, 2)
        self.portfolio_change_widget_hlayout.addLayout(self.portfolio_change_widget_vlayout)
        self.portfolio_global_widget_layout.addWidget(self.portfolio_change_widget)
        self.total_profit_widget = QtWidgets.QWidget(self.layoutWidget_3)
        self.total_profit_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.total_profit_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.total_profit_widget.setObjectName("total_profit_widget")
        self.horizontalLayoutWidget_8 = QtWidgets.QWidget(self.total_profit_widget)
        self.horizontalLayoutWidget_8.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_8.setObjectName("horizontalLayoutWidget_8")
        self.total_profit_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_8)
        self.total_profit_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.total_profit_widget_hlayout.setObjectName("total_profit_widget_hlayout")
        self.total_profit_widget_vlayout = QtWidgets.QVBoxLayout()
        self.total_profit_widget_vlayout.setContentsMargins(0, 0, 0, 0)
        self.total_profit_widget_vlayout.setObjectName("total_profit_widget_vlayout")
        self.total_profit_widget_value = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.total_profit_widget_value.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.total_profit_widget_value.setObjectName("total_profit_widget_value")
        self.total_profit_widget_vlayout.addWidget(self.total_profit_widget_value)
        self.total_profit_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_8)
        self.total_profit_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.total_profit_widget_label.setObjectName("total_profit_widget_label")
        self.total_profit_widget_vlayout.addWidget(self.total_profit_widget_label)
        self.total_profit_widget_vlayout.setStretch(0, 2)
        self.total_profit_widget_vlayout.setStretch(1, 1)
        self.total_profit_widget_hlayout.addLayout(self.total_profit_widget_vlayout)
        self.portfolio_global_widget_layout.addWidget(self.total_profit_widget)
        self.portfolio_number_of_coins_widget = QtWidgets.QWidget(self.layoutWidget_3)
        self.portfolio_number_of_coins_widget.setMaximumSize(QtCore.QSize(16777215, int(90 * self.ratio)))
        self.portfolio_number_of_coins_widget.setStyleSheet("background: #232323;\n"
"border-radius: " + str(int(24 * self.ratio)) + "px;\n"
"")
        self.portfolio_number_of_coins_widget.setObjectName("portfolio_number_of_coins_widget")
        self.horizontalLayoutWidget_9 = QtWidgets.QWidget(self.portfolio_number_of_coins_widget)
        self.horizontalLayoutWidget_9.setGeometry(QtCore.QRect(0, 0, int(281 * self.ratio), int(91 * self.ratio)))
        self.horizontalLayoutWidget_9.setObjectName("horizontalLayoutWidget_9")
        self.portfolio_number_of_coins_widget_hlayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_9)
        self.portfolio_number_of_coins_widget_hlayout.setContentsMargins(int(25 * self.ratio), int(20 * self.ratio), int(25 * self.ratio), int(20 * self.ratio))
        self.portfolio_number_of_coins_widget_hlayout.setObjectName("portfolio_number_of_coins_widget_hlayout")
        self.portfolio_number_of_coins_widget_vlayout = QtWidgets.QVBoxLayout()
        self.portfolio_number_of_coins_widget_vlayout.setObjectName("portfolio_number_of_coins_widget_vlayout")
        self.portfolio_number_of_coins_widgetvalue = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.portfolio_number_of_coins_widgetvalue.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: white;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(24 * self.ratio)) + "px;")
        self.portfolio_number_of_coins_widgetvalue.setObjectName("portfolio_number_of_coins_widgetvalue")
        self.portfolio_number_of_coins_widget_vlayout.addWidget(self.portfolio_number_of_coins_widgetvalue)
        self.portfolio_number_of_coins_widget_label = QtWidgets.QLabel(self.horizontalLayoutWidget_9)
        self.portfolio_number_of_coins_widget_label.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: #808080;\n"
"font-family: Arial, Helvetica, sans-serif;\n"
"font-size: " + str(int(18 * self.ratio)) + "px;")
        self.portfolio_number_of_coins_widget_label.setObjectName("portfolio_number_of_coins_widget_label")
        self.portfolio_number_of_coins_widget_vlayout.addWidget(self.portfolio_number_of_coins_widget_label)
        self.portfolio_number_of_coins_widget_vlayout.setStretch(0, 2)
        self.portfolio_number_of_coins_widget_vlayout.setStretch(1, 1)
        self.portfolio_number_of_coins_widget_hlayout.addLayout(self.portfolio_number_of_coins_widget_vlayout)
        self.portfolio_global_widget_layout.addWidget(self.portfolio_number_of_coins_widget)
        spacerItem8 = QtWidgets.QSpacerItem(int(40 * self.ratio), int(20 * self.ratio), QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.portfolio_global_widget_layout.addItem(spacerItem8)
        self.portfolio_global_widget_layout.setStretch(0, 1)
        self.portfolio_global_widget_layout.setStretch(1, 1)
        self.portfolio_global_widget_layout.setStretch(2, 1)
        self.portfolio_global_widget_layout.setStretch(3, 1)
        self.portfolio_global_widget_layout.setStretch(4, 2)
        self.portfolio_layout.addLayout(self.portfolio_global_widget_layout)
        self.portfolio_table_widget = QtWidgets.QTableWidget(self.layoutWidget_3)
        self.portfolio_table_widget.setAutoFillBackground(False)
        self.portfolio_table_widget.setStyleSheet("QHeaderView::section {\n"
"    background-color:  #232323;\n"
"    border: none;\n"
"    height: " + str(int(32 * self.ratio)) + "px;\n"
"    color:white;\n"
"    font-family: Arial, Helvetica, sans-serif;\n"
"    font-size: " + str(int(16 * self.ratio)) + "px;\n"
"    font-weight: 500;\n"
"}\n"
"QFrame {\n"
"    background: rgba(0, 0, 0, 0);\n"
"    border: none;\n"
"}    \n"
"QTableWidget  {\n"
"    gridline-color: #232323;\n"
"}    \n"
"")
        self.portfolio_table_widget.setObjectName("portfolio_table_widget")
        self.portfolio_table_widget.setColumnCount(8)
        self.portfolio_table_widget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.portfolio_table_widget.setHorizontalHeaderItem(7, item)
        self.portfolio_table_widget.horizontalHeader().setDefaultSectionSize(int(200 * self.ratio))
        self.portfolio_table_widget.horizontalHeader().setHighlightSections(True)
        # self.portfolio_table_widget.horizontalHeader().setMinimumSectionSize(int(200 * self.ratio))
        self.portfolio_table_widget.horizontalHeader().setStretchLastSection(True)
        self.portfolio_table_widget.verticalHeader().setVisible(False)
        # self.portfolio_table_widget.verticalHeader().setMinimumSectionSize(int(30 * self.ratio))
        self.portfolio_table_widget.verticalHeader().setSortIndicatorShown(False)
        self.portfolio_table_widget.verticalHeader().setStretchLastSection(False)
        self.portfolio_layout.addWidget(self.portfolio_table_widget)
        self.portfolio_layout.setStretch(0, 1)
        self.portfolio_layout.setStretch(1, 5)
        self.stackedWidget.addWidget(self.portfolio_widget)
        self.main_layout.addWidget(self.stackedWidget)
        self.main_layout.setStretch(1, 1)
        
        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.__cfgTable(self.master_table_widget)
        self.__cfgTable(self.favourites_table)
        self.__cfgTable(self.portfolio_table_widget)

    def __cfgTable(self, table_widget):
        table_widget.setEditTriggers(QAbstractItemView.NoEditTriggers)
        table_widget.setFocusPolicy(Qt.NoFocus)
        table_widget.setSelectionMode(QAbstractItemView.NoSelection)       
       
        table_widget.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        table_widget.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        table_widget.horizontalHeader().setSectionResizeMode(QHeaderView.Fixed)
        table_widget.verticalHeader().setMaximumSectionSize(int(36 * self.ratio))
        table_widget.verticalHeader().setSectionResizeMode(QHeaderView.Fixed)

        table_widget.setColumnWidth(0, int(91 * self.ratio))
        table_widget.setColumnWidth(1, int(573 * self.ratio))
        table_widget.setColumnWidth(2, int(282 * self.ratio))
        table_widget.setColumnWidth(3, int(127 * self.ratio))
        table_widget.setColumnWidth(4, int(127 * self.ratio))
        table_widget.setColumnWidth(5, int(127 * self.ratio))
        table_widget.setColumnWidth(6, int(255 * self.ratio))

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.quit_button.setText(_translate("Form", "X"))
        self.favourites_button.setText(_translate("Form", "Favourites"))
        self.my_portfolio_button.setText(_translate("Form", "My portfolio"))
        self.market_cap_prefix_label.setText(_translate("Form", "Today\'s total cryptocurrency market cap is:"))
        self.market_cap_suffix_label.setText(_translate("Form", "0.0 Trillion, a 0.0% increase in the last 24 hours."))
        self.market_cap_widget_value.setText(_translate("Form", "$0,000,000,000,000"))
        self.market_cap_widget_label.setText(_translate("Form", "Market Capitalization"))
        self.trading_volume_widget_value.setText(_translate("Form", "$0,000,000,000"))
        self.trading_volume_widget_label.setText(_translate("Form", "24h Trading Volume"))
        self.btc_dominance_widget_value.setText(_translate("Form", "50.00%"))
        self.btc_dominance_widget_label.setText(_translate("Form", "Bitcoin Market Cap Dominance"))
        self.number_of_coins_widget_value.setText(_translate("Form", "0,000"))
        self.number_of_coins_widget_label.setText(_translate("Form", "Number of Coins"))
        item = self.master_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "#"))
        item = self.master_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Coin"))
        item = self.master_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Price"))
        item = self.master_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "1h"))
        item = self.master_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "24h"))
        item = self.master_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "7d"))
        item = self.master_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "24h Volume"))
        item = self.master_table_widget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Market cap"))
        self.rank_label.setText(_translate("Form", "Rank #1"))
        self.details_coin_name_label.setText(_translate("Form", "Bitcoin"))
        self.details_portfolio_bought_amount_label.setText(_translate("Form", "Bought amount"))
        self.details_portfolio_price_label.setText(_translate("Form", "Price (USD)"))
        self.details_coin_symbol_label.setText(_translate("Form", "BTC"))
        self.details_coin_price_label.setText(_translate("Form", "$27,811.46"))
        self.details_coin_change_label.setText(_translate("Form", "0.4%"))
        self.details_market_cap_widget_value.setText(_translate("Form", "$539,781,593,350"))
        self.details_market_cap_widget_label.setText(_translate("Form", "Market Capitalization"))
        self.details_trading_volume_widget_value.setText(_translate("Form", "$14,100,540,089"))
        self.details_trading_volume_widget_label.setText(_translate("Form", "24h Trading Volume"))
        self.details_circulating_supply_widget_value.setText(_translate("Form", "19,388,387"))
        self.details_circulating_supply_widget_label.setText(_translate("Form", "Circulating Supply"))
        self.details_all_time_high_widget_value.setText(_translate("Form", "$69,044.77"))
        self.details_all_time_high_widget_label.setText(_translate("Form", "All-Time High"))
        self.details_all_time_low_widget_value.setText(_translate("Form", "$67.81"))
        self.details_all_time_low_widget_label.setText(_translate("Form", "All-Time Low"))
        item = self.time_change_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "1h"))
        item = self.time_change_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "24h"))
        item = self.time_change_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "7d"))
        item = self.time_change_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "14d"))
        item = self.time_change_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "30d"))
        item = self.time_change_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "1y"))
        self.favourites_number_of_favourite_coins_label.setText(_translate("Form", "Number of favourite coins:"))
        self.favourites_number_of_favourite_coins_value.setText(_translate("Form", "0"))
        item = self.favourites_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "#"))
        item = self.favourites_table.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Coin"))
        item = self.favourites_table.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Price"))
        item = self.favourites_table.horizontalHeaderItem(3)
        item.setText(_translate("Form", "1h"))
        item = self.favourites_table.horizontalHeaderItem(4)
        item.setText(_translate("Form", "24h"))
        item = self.favourites_table.horizontalHeaderItem(5)
        item.setText(_translate("Form", "7d"))
        item = self.favourites_table.horizontalHeaderItem(6)
        item.setText(_translate("Form", "24h Volume"))
        item = self.favourites_table.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Market cap"))
        self.portfolio_total_balance_widget_value.setText(_translate("Form", "$0.00"))
        self.portfolio_total_balance_widget_label.setText(_translate("Form", "Total Balance"))
        self.portfolio_change_widget_value.setText(_translate("Form", "$0.00"))
        self.portfolio_change_widget_label.setText(_translate("Form", "24h Portfolio Change"))
        self.total_profit_widget_value.setText(_translate("Form", "$0.00"))
        self.total_profit_widget_label.setText(_translate("Form", "Total Profit/Loss"))
        self.portfolio_number_of_coins_widgetvalue.setText(_translate("Form", "0"))
        self.portfolio_number_of_coins_widget_label.setText(_translate("Form", "Number of Coins in Portfolio"))
        item = self.portfolio_table_widget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "#"))
        item = self.portfolio_table_widget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Coin"))
        item = self.portfolio_table_widget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Price"))
        item = self.portfolio_table_widget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "1h"))
        item = self.portfolio_table_widget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "24h"))
        item = self.portfolio_table_widget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "7d"))
        item = self.portfolio_table_widget.horizontalHeaderItem(6)
        item.setText(_translate("Form", "Holdings"))
        item = self.portfolio_table_widget.horizontalHeaderItem(7)
        item.setText(_translate("Form", "Profit/Loss"))

